language: python
python:
  - "3.6.1"
# command install dependencies
install:
  - pip install -r requirements.txt

#setup db
services:
  -postgresql
  
#create db before script runs
before_script:
  - psql -c 'create database test_db;' -U postgres

# command tp run tests
script: nosetests --with-coverage
after_success: coveralls