language: python
python:
  - "3.6.1"
# command install dependencies
install:
  - pip install -r requirements.txt
  - pip install gunicorn

#setup db
services:
  -postgresql
  
#create db before script runs
before_script:
  - psql -c 'create database test_db;' -U postgres
  - python manage.py db init
  - python manage.py db migrate
  - python manage.py db upgrade


# command to run tests
script: 
  - source .env
  - nosetests --with-coverage
after_success: coveralls