- name: Install postgres
  apt:
    name: postgresql-9.5

- shell: apt-get update

- name: Install client
  apt:
    name: postgresql-contrib-9.5

- name: Configure postgres
  template:
    src: templates/pg_hba.conf
    dest: /etc/postgresql/9.5/main/pg_hba.conf

- name: Restart postgres
  service:
    name: postgresql
    state: restarted

    