- name: Install nginx
  apt:
    name:  nginx
    state: present

- shell: apt-get update

- name: copy nginx configuration
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/sites-available/default

- name: Create symlinks
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify:
    - restart nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes